package com.game.geodetective.screen;

public enum ScreenCode {
	UNKNOWN,
	CONTINUE,
	TRANSITION_TITLE,
	TRANSITION_CREDITS,
	TRANSITION_LEVEL_SELECT,
	TRANSITION_JOURNAL,
	TRANSITION_LEVEL,
	TRANSITION_LEVEL_OPTIONS,
	TRANSITION_DEATH,
	TRANSITION_KILL,
	TRANSITION_END_LEVEL,
	TRANSITION_END_GAME
}
